"""create tables

Revision ID: 142be61a7530
Revises: 
Create Date: 2024-12-21 18:26:59.443862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142be61a7530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
