"""create tables

Revision ID: 2e6cc4d3b936
Revises: a34ee9752e3e
Create Date: 2025-01-08 10:41:23.866021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6cc4d3b936'
down_revision = 'a34ee9752e3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=1024), nullable=True))
    op.drop_index('ix_users_portrait', table_name='users')
    op.create_index(op.f('ix_users_avatar'), 'users', ['avatar'], unique=False)
    op.drop_column('users', 'portrait')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('portrait', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_avatar'), table_name='users')
    op.create_index('ix_users_portrait', 'users', ['portrait'], unique=False)
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
