"""update

Revision ID: 3ec395a8f4cf
Revises: e388e60b4699
Create Date: 2025-01-21 15:43:30.994127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ec395a8f4cf'
down_revision = 'e388e60b4699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'new_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sessions', 'messages_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'messages_context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('sessions', 'new_message',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
