"""create users table

Revision ID: 798587044c5e
Revises: 895a5310e0fc
Create Date: 2024-12-07 14:12:47.253810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798587044c5e'
down_revision = '895a5310e0fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
