"""update

Revision ID: 7d2e4691a87d
Revises: a5974068e223
Create Date: 2025-01-15 14:38:25.355146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2e4691a87d'
down_revision = 'a5974068e223'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'system_prompt',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('characters', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'visibility',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('characters', 'tts',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_index(op.f('ix_characters_likes'), 'characters', ['likes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_likes'), table_name='characters')
    op.alter_column('characters', 'tts',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('characters', 'visibility',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('characters', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'system_prompt',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###
