"""create tables

Revision ID: 841814b4ea87
Revises: 
Create Date: 2024-12-23 10:02:00.522785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '841814b4ea87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('background', sa.String(length=1024), nullable=True),
    sa.Column('portrait', sa.String(length=256), nullable=True),
    sa.Column('voice_id', sa.String(length=15), nullable=True),
    sa.Column('system_prompt', sa.String(length=1024), nullable=False),
    sa.Column('tts', sa.String(length=256), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=True)
    op.create_index(op.f('ix_characters_system_prompt'), 'characters', ['system_prompt'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_index(op.f('ix_characters_visibility'), 'characters', ['visibility'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('character_name', sa.String(length=64), nullable=False),
    sa.Column('character_portrait', sa.String(length=256), nullable=True),
    sa.Column('new_message', sa.Text(), nullable=False),
    sa.Column('messages_context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_character_id'), 'sessions', ['character_id'], unique=False)
    op.create_index(op.f('ix_sessions_character_name'), 'sessions', ['character_name'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_name'), 'sessions', ['user_name'], unique=False)
    op.create_index('ix_user_character', 'sessions', ['user_id', 'character_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('platform', postgresql.ENUM('Web', 'Android', 'Ios', 'MiniProgram', name='platform_enum'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=48), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('finish_reason', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_language'), 'messages', ['language'], unique=False)
    op.create_index(op.f('ix_messages_model'), 'messages', ['model'], unique=False)
    op.create_index(op.f('ix_messages_platform'), 'messages', ['platform'], unique=False)
    op.create_index(op.f('ix_messages_request_id'), 'messages', ['request_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index('ix_session_platform', 'messages', ['session_id', 'platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_platform', table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_request_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_platform'), table_name='messages')
    op.drop_index(op.f('ix_messages_model'), table_name='messages')
    op.drop_index(op.f('ix_messages_language'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_user_character', table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_name'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_character_name'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_character_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_characters_visibility'), table_name='characters')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_system_prompt'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
