"""create users table

Revision ID: 895a5310e0fc
Revises: b5121f2eb9b1
Create Date: 2024-12-07 14:11:10.952159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895a5310e0fc'
down_revision = 'b5121f2eb9b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
