"""update

Revision ID: a2779b93ac73
Revises: e234eb640ddf
Create Date: 2025-01-14 17:46:45.564781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2779b93ac73'
down_revision = 'e234eb640ddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
