"""create tables

Revision ID: a34ee9752e3e
Revises: 841814b4ea87
Create Date: 2025-01-08 10:07:03.666452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34ee9752e3e'
down_revision = '841814b4ea87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('portrait', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_users_portrait'), 'users', ['portrait'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_portrait'), table_name='users')
    op.drop_column('users', 'portrait')
    # ### end Alembic commands ###
