"""create table

Revision ID: ad633174a482
Revises: 76c9b835fd42
Create Date: 2024-12-19 21:59:58.718282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad633174a482'
down_revision = '76c9b835fd42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_characters_user_prompt', table_name='characters')
    op.drop_column('characters', 'user_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('user_prompt', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_index('ix_characters_user_prompt', 'characters', ['user_prompt'], unique=False)
    # ### end Alembic commands ###
