"""create users table

Revision ID: b5121f2eb9b1
Revises: ed3b9323e165
Create Date: 2024-12-07 14:05:49.587308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5121f2eb9b1'
down_revision = 'ed3b9323e165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
