"""update

Revision ID: c94ff8a218b2
Revises: e606fdf081ad
Create Date: 2025-01-29 17:45:18.175153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c94ff8a218b2'
down_revision = 'e606fdf081ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_character_name', table_name='sessions')
    op.drop_column('sessions', 'character_name')
    op.drop_column('sessions', 'character_avatars')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('character_avatars', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('character_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index('ix_sessions_character_name', 'sessions', ['character_name'], unique=False)
    # ### end Alembic commands ###
