"""update

Revision ID: e606fdf081ad
Revises: 03dc4e32d83f
Create Date: 2025-01-29 16:48:34.620918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e606fdf081ad'
down_revision = '03dc4e32d83f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('character_avatars', sa.JSON(), nullable=True))
    op.drop_column('sessions', 'character_avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('character_avatar', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'character_avatars')
    # ### end Alembic commands ###
